config/routes.rb
Rails.application.routes.draw do
  resources :welcomes
  resources :properties
  resources :champion_properties
  resources :champion_teams
  resources :attributes
  resources :users
  resources :categories
  resources :teams
  resources :champions

  root :to => 'welcomes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/attributes_controller.rb
class AttributesController < ApplicationController
  before_action :set_attribute, only: [:show, :edit, :update, :destroy]

  # GET /attributes
  # GET /attributes.json
  def index
    @attributes = Attribute.all
  end

  # GET /attributes/1
  # GET /attributes/1.json
  def show
  end

  # GET /attributes/new
  def new
    @attribute = Attribute.new
  end

  # GET /attributes/1/edit
  def edit
  end

  # POST /attributes
  # POST /attributes.json
  def create
    @attribute = Attribute.new(attribute_params)

    respond_to do |format|
      if @attribute.save
        format.html { redirect_to @attribute, notice: 'Attribute was successfully created.' }
        format.json { render :show, status: :created, location: @attribute }
      else
        format.html { render :new }
        format.json { render json: @attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attributes/1
  # PATCH/PUT /attributes/1.json
  def update
    respond_to do |format|
      if @attribute.update(attribute_params)
        format.html { redirect_to @attribute, notice: 'Attribute was successfully updated.' }
        format.json { render :show, status: :ok, location: @attribute }
      else
        format.html { render :edit }
        format.json { render json: @attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attributes/1
  # DELETE /attributes/1.json
  def destroy
    @attribute.destroy
    respond_to do |format|
      format.html { redirect_to attributes_url, notice: 'Attribute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attribute
      @attribute = Attribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attribute_params
      params.fetch(:attribute, {})
    end
end

app/helpers/attributes_helper.rb
module AttributesHelper
end

app/views/attributes/_form.html.erb
<%= form_with(model: attribute, local: true) do |form| %>
  <% if attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attribute.errors.count, "error") %> prohibited this attribute from being saved:</h2>

      <ul>
      <% attribute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attributes/edit.html.erb
<h1>Editing Attribute</h1>

<%= render 'form', attribute: @attribute %>

<%= link_to 'Show', @attribute %> |
<%= link_to 'Back', attributes_path %>

app/views/attributes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attributes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attributes.each do |attribute| %>
      <tr>
        <td><%= link_to 'Show', attribute %></td>
        <td><%= link_to 'Edit', edit_attribute_path(attribute) %></td>
        <td><%= link_to 'Destroy', attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attribute', new_attribute_path %>

app/views/attributes/new.html.erb
<h1>New Attribute</h1>

<%= render 'form', attribute: @attribute %>

<%= link_to 'Back', attributes_path %>

app/views/attributes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_attribute_path(@attribute) %> |
<%= link_to 'Back', attributes_path %>