config/routes.rb
Rails.application.routes.draw do
  resources :welcomes
  resources :properties
  resources :champion_properties
  resources :champion_teams
  resources :attributes
  resources :users
  resources :categories
  resources :teams
  resources :champions

  root :to => 'welcomes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/champion_property.rb
class ChampionProperty < ApplicationRecord
  belongs_to :property
  belongs_to :category
  belongs_to :champions
end

app/controllers/champion_properties_controller.rb
class ChampionPropertiesController < ApplicationController
  before_action :set_champion_property, only: [:show, :edit, :update, :destroy]

  # GET /champion_properties
  # GET /champion_properties.json
  def index
    @champion_properties = ChampionProperty.all
  end

  # GET /champion_properties/1
  # GET /champion_properties/1.json
  def show
  end

  # GET /champion_properties/new
  def new
    @champion_property = ChampionProperty.new
  end

  # GET /champion_properties/1/edit
  def edit
  end

  # POST /champion_properties
  # POST /champion_properties.json
  def create
    @champion_property = ChampionProperty.new(champion_property_params)

    respond_to do |format|
      if @champion_property.save
        format.html { redirect_to @champion_property, notice: 'Champion property was successfully created.' }
        format.json { render :show, status: :created, location: @champion_property }
      else
        format.html { render :new }
        format.json { render json: @champion_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /champion_properties/1
  # PATCH/PUT /champion_properties/1.json
  def update
    respond_to do |format|
      if @champion_property.update(champion_property_params)
        format.html { redirect_to @champion_property, notice: 'Champion property was successfully updated.' }
        format.json { render :show, status: :ok, location: @champion_property }
      else
        format.html { render :edit }
        format.json { render json: @champion_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champion_properties/1
  # DELETE /champion_properties/1.json
  def destroy
    @champion_property.destroy
    respond_to do |format|
      format.html { redirect_to champion_properties_url, notice: 'Champion property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_champion_property
      @champion_property = ChampionProperty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def champion_property_params
      params.fetch(:champion_property, {})
    end
end

app/helpers/champion_properties_helper.rb
module ChampionPropertiesHelper
end

app/views/champion_properties/_form.html.erb
<%= form_with(model: champion_property, local: true) do |form| %>
  <% if champion_property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(champion_property.errors.count, "error") %> prohibited this champion_property from being saved:</h2>

      <ul>
      <% champion_property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/champion_properties/edit.html.erb
<h1>Editing Champion Property</h1>

<%= render 'form', champion_property: @champion_property %>

<%= link_to 'Show', @champion_property %> |
<%= link_to 'Back', champion_properties_path %>

app/views/champion_properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Champion Properties</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @champion_properties.each do |champion_property| %>
      <tr>
        <td><%= link_to 'Show', champion_property %></td>
        <td><%= link_to 'Edit', edit_champion_property_path(champion_property) %></td>
        <td><%= link_to 'Destroy', champion_property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Champion Property', new_champion_property_path %>

app/views/champion_properties/new.html.erb
<h1>New Champion Property</h1>

<%= render 'form', champion_property: @champion_property %>

<%= link_to 'Back', champion_properties_path %>

app/views/champion_properties/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_champion_property_path(@champion_property) %> |
<%= link_to 'Back', champion_properties_path %>